name: Build Docker Image

on:
  release:
    types: [ published ]
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Devel Image
        uses: docker/build-push-action@v2
        if: ${{ github.event_name != 'release' || github.event.action != 'published' }}
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            kezhenxu94/kube-scavenger:${{ github.event.release.tag_name || 'devel' }}

      - name: Tag and Push Latest Image
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            kezhenxu94/kube-scavenger:latest
            kezhenxu94/kube-scavenger:${{ github.event.release.tag_name}}
