name: Build Docker Image

on:
  release:
    types: [ published ]
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        # if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true # ${{ github.event_name == 'release' && github.event.action == 'published' }}
          tags: |
            kezhenxu94/kube-scavenger:latest
            kezhenxu94/kube-scavenger:${{ github.event.release.tag_name || 'temp' }}
